//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWDataEditorPaied.Forms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AiPolicyEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AiPolicyEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PWDataEditorPaied.Forms.AiPolicyEditor", typeof(AiPolicyEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=419,Y=17}.
        /// </summary>
        public static System.Drawing.Point contextMenuAction_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("contextMenuAction.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=854,Y=17}.
        /// </summary>
        public static System.Drawing.Point contextMenuEditCondition_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("contextMenuEditCondition.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=251,Y=18}.
        /// </summary>
        public static System.Drawing.Point contextMenuPolicy_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("contextMenuPolicy.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=575,Y=18}.
        /// </summary>
        public static System.Drawing.Point contextMenuProcedure_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("contextMenuProcedure.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=172,Y=47}.
        /// </summary>
        public static System.Drawing.Point contextMenuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("contextMenuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=47}.
        /// </summary>
        public static System.Drawing.Point contextMenuStrip3_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("contextMenuStrip3.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        public static System.Drawing.PointF jAnimation1_BlindCoeff {
            get {
                object obj = ResourceManager.GetObject("jAnimation1.BlindCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        public static System.Drawing.PointF jAnimation1_MosaicCoeff {
            get {
                object obj = ResourceManager.GetObject("jAnimation1.MosaicCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        public static System.Drawing.PointF jAnimation1_MosaicShift {
            get {
                object obj = ResourceManager.GetObject("jAnimation1.MosaicShift", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=0}.
        /// </summary>
        public static System.Drawing.PointF jAnimation1_ScaleCoeff {
            get {
                object obj = ResourceManager.GetObject("jAnimation1.ScaleCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.PointF similar to {X=0, Y=1}.
        /// </summary>
        public static System.Drawing.PointF jAnimation1_SlideCoeff {
            get {
                object obj = ResourceManager.GetObject("jAnimation1.SlideCoeff", resourceCulture);
                return ((System.Drawing.PointF)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap jPictureBox1_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("jPictureBox1.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap jPictureBox2_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("jPictureBox2.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap jPictureBox5_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("jPictureBox5.BackgroundImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=17,Y=17}.
        /// </summary>
        public static System.Drawing.Point OpenDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("OpenDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap resource_Image {
            get {
                object obj = ResourceManager.GetObject("resource.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=134,Y=17}.
        /// </summary>
        public static System.Drawing.Point SaveDialog_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("SaveDialog.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
